### PR TITLE
added alarm clock using python

### PR DESCRIPTION
**Pull request by rutvikgondaliya**

### CODE REVIEW

**Comment by avinash201199** [comment]
Add more information in readme file atleast 5,6 line with image

**Comment by rutvikgondaliya** [comment]
Okay

**Comment by rutvikgondaliya** [comment]
now

**Comment by rutvikgondaliya** [comment]
now @avinash201199

**Comment by rutvikgondaliya** [comment]
Thank you sir

**Comment by avinash201199** [comment]
your welcome :)
follow for more

**Comment by rutvikgondaliya** [comment]
Dear sir,

Please check my pull request
https://github.com/avinash201199/Paid-Internship-List/pull/7

**Pull request merged**
